EBNF of C++ : http://www.externsoft.ch/download/cpp-iso.html
left or right associativity: https://stackoverflow.com/questions/41784524/preferred-way-of-removing-left-recursion-of-ebnf

//top line has lowest precedence:
//these are not function calls but structs:

echoComment = '!//' rest_of_line

statements = '/#' statementBlock '#/' |

statementsBlock = statement {'; statement [';']}

statement = '!' statementBody |
            '#' statementBody

statementBody = addExpr |
            assignment

assignment = id '=' addExpr

addExpr = multExpr |  
          addExpr ("+" | "-") multExpr 

multExpr = powerExpr |
           multExpr ("*" | "/") powerExpr |
           impliedMultExpr

impliedMultExpr = const id |
                  multExpr '(' |
                  '(' addExpr ')' (id | const)

powerExpr = unitExpr |
           powerExpr "^" unitExpr

unitExpr = postFixExpr |
           postFixExpr unit

postFixExpr = primaryExpr |
            postFixExpr '.' [ id ] |
            primaryExpr (INC | DEC)
            
primaryExpr = const | 
              id | 
              "(", addExpr, ")" |
              callExpr |
              absExpr

absExpr = '|' addExpr '|'

const = {-} [0..9] unit |
        QUOT formattedValue QUOT

formattedValue = dateValue //for now, only dates.

unit = id

callExpr = funcId '(' exprList ')'
